/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recordatorio;

import BaseDatos.ConexionMySQL;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ANDRES TALERO
 */
public class fechasVencimiento extends javax.swing.JFrame {
Date ahora = new Date();
    /**
     * Creates new form fechasVencimiento
     */
    public fechasVencimiento() {
        initComponents();
        cargardatos();
        cargarnumero();
    //    jTidvencimiento.setEnabled(false);
    }

    
    
    
    
    public void cargarnumero(){
        
      ConexionMySQL c = new ConexionMySQL();
        Connection cn = c.getConnection();
         Statement st2;
        int aux =0; 
    try {
         
     String   sql1="select nullif(max(idvencimiento),0) as cantidad from fechasimpuesto;";
         
              st2 = cn.createStatement();
              ResultSet rs2 = st2.executeQuery(sql1);
              rs2.next();
              String aux1 =rs2.getString("cantidad");
              
              if(aux1==null){
              aux=0;
              }
              else{
              aux=Integer.parseInt(aux1);
              
              }
              
     } catch (SQLException ex) {
         
         JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA LISTA DE PERIOCIDAD ");
         
     }
    aux++;
       jTidvencimiento.setText(aux+"");
    }
    
    
    public void cargardatos() {
    
        
    String sSQL="";
    
    
    
    sSQL ="select nombre from impuesto where idimpuesto = idimpuesto;";
    try 
        {
            ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
       //  cmbimpuesto.removeAllItems();
         
         
         while(rs.next())
         {
       //  cmbimpuesto.addItem(rs.getString(1));
         
          }} 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA LISTA DE IMPUESTOS ");
        }
    



}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTidvencimiento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTultimodigito = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbimpuesto = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jDfecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FECHAS VENCIMIENTO");

        jLabel1.setText("ID VENCIMIENTO");

        jTidvencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidvencimientoActionPerformed(evt);
            }
        });

        jLabel2.setText("ULTIMO(S) DIGITO(S)");

        jTultimodigito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTultimodigitoActionPerformed(evt);
            }
        });

        jLabel3.setText("IMPUESTO");

        jLabel4.setText("FECHA");

        btnGrabar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("ACTUALIZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidvencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTultimodigito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbimpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultar)))
                        .addGap(234, 234, 234))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTidvencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTultimodigito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbimpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(btnSalir))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     
      
    
    
   
    
    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn=mysql.getConnection();
        Recordatorio re =new  Recordatorio();
                     
        String sSQL="";
        String mensaje="";
        
          
        int id=0,impuesto=0,ultimodigito=0;
        String fecha="";
        
        id = Integer.parseInt(jTidvencimiento.getText());           
        ultimodigito= Integer.parseInt(jTultimodigito.getText());
        impuesto = cmbimpuesto.getSelectedIndex()+1;
        
        fecha=re.getFechaActual(jDfecha.getDate());
                               
       
            sSQL="INSERT INTO fechasimpuesto(idvencimiento,ultimosdigitos,idimpuesto,fecha) VALUES(?,?,?,?)";
            mensaje="Los Datos se han Insertado de Manera Satisfactoria";
            
            jTidvencimiento.setText("");
            jTultimodigito.setText("");
            cmbimpuesto.setSelectedIndex(0);
            jDfecha.setDate(ahora);
            
            
                 
        
        try {
            
            
            
            PreparedStatement pst =cn.prepareStatement(sSQL);

            pst.setInt(1,id);
            pst.setInt(2,ultimodigito);
            pst.setInt(3,impuesto);
            pst.setString(4, fecha);
            
            
            

            int n=pst.executeUpdate();

            if(n > 0){

                JOptionPane.showMessageDialog(null,mensaje);

            }
            else {
                JOptionPane.showMessageDialog(null, "no se ha insertado nada ");

            }

        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        } 
               
        cargarnumero();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void jTultimodigitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTultimodigitoActionPerformed
        jTultimodigito.transferFocus();
    }//GEN-LAST:event_jTultimodigitoActionPerformed

    private void jTidvencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidvencimientoActionPerformed
       jTidvencimiento.transferFocus();
        Cargarfechasimpuesto(jTidvencimiento.getText());
    }//GEN-LAST:event_jTidvencimientoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        cargarnumero();
        jTultimodigito.setText("");
        cmbimpuesto.setSelectedIndex(0);
       
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    
    void Cargarfechasimpuesto(String valor)
    {
    Recordatorio re =new Recordatorio();
    String[] registro =new String[3];    
    String sSQL="";
     
    ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
     

    if(valor.equals(""))
    JOptionPane.showMessageDialog(null,"EL CAMPO ESTA VACIO");
       
    else  
    sSQL ="select ultimosdigitos,idimpuesto,fecha from fechasimpuesto where idvencimiento = "+valor+"; ";
           try 
        {
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         
         
         while(rs.next())
         {
         
         registro[0]= rs.getString("ultimosdigitos");
             jTultimodigito.setText(registro[0]);
         registro[1]=rs.getString("idimpuesto");
         cmbimpuesto.setSelectedIndex(Integer.parseInt(registro[1])-1);
         registro[2]=rs.getString("fecha");
             System.out.println(registro[2]);
         
         jDfecha.setDate(re.ParseFecha(registro[2]));
         
         }
         
         
        } 
        catch (SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex);
            
        }
           
          
           
         
    }
    
    
    
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        
        
        
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn=mysql.getConnection();
        Recordatorio re =new  Recordatorio();
        
       
        String sSQL="";
        String mensaje="";
        
        int idven=0,ul=0,impuesto=0;
        String fecha="";
        idven = Integer.parseInt(jTidvencimiento.getText());           
        ul = Integer.parseInt(jTultimodigito.getText());
        impuesto = cmbimpuesto.getSelectedIndex()+1;
         fecha=re.getFechaActual(jDfecha.getDate());
        
        sSQL="UPDATE fechasimpuesto SET idvencimiento=?,ultimosdigitos=?, idimpuesto=?,fecha=? WHERE idvencimiento= "+idven;

            mensaje="Los Datos se han actualizado de Manera Satisfactoria";
            
             jTidvencimiento.setText("");
            jTultimodigito.setText("");
            cmbimpuesto.setSelectedIndex(0);
            jDfecha.setDate(ahora);
            cargarnumero();
            
            
            
            try {
            PreparedStatement pst =cn.prepareStatement(sSQL);

            pst.setInt(1,idven);
            pst.setInt(2,ul);
            pst.setInt(3,impuesto);
            pst.setString(4 ,fecha);

            int n=pst.executeUpdate();

            if(n > 0){

                JOptionPane.showMessageDialog(null,mensaje);

            }
            else {
                JOptionPane.showMessageDialog(null, "no se ha actualziado nada ");

            }

        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       ConexionMySQL mysql = new ConexionMySQL();
        Connection cn=mysql.getConnection();
        Recordatorio re =new Recordatorio();
        String sSQL="";
        String mensaje="";
        
        int idven=0,n=0;
        
        idven = Integer.parseInt(jTidvencimiento.getText());           
        
        
        try
                      {
                        JOptionPane optionPane = new JOptionPane();
	                    Object[] opciones={"Sí","No"};
	                    //Dialogo modal SI_NO
	                     int ret = JOptionPane.showOptionDialog(null,"Desea Borrar? ","Confirmar",
                         JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
	                     //Si la opcion escogida es Si
	                     if(ret==JOptionPane.YES_OPTION)
                         {
                             
                             
                             Statement stmt = cn.createStatement();
                              n = stmt.executeUpdate("delete from fechasimpuesto WHERE idvencimiento= "+idven);
                              JOptionPane.showMessageDialog( null, "Registro Borrado "  ,
                                "Sistema", JOptionPane.ERROR_MESSAGE );
                         }
                      } catch (Exception e)
                      {
                               e.printStackTrace();
                               JOptionPane.showMessageDialog(null, "Ocurrio Un error" , "Atencion",
                               JOptionPane.INFORMATION_MESSAGE);
                      }
             jTidvencimiento.setText("");
            jTultimodigito.setText("");
            cmbimpuesto.setSelectedIndex(0);
          jDfecha.setDate(ahora);
            cargarnumero();
            
       
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fechasVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fechasVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fechasVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fechasVencimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fechasVencimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbimpuesto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTidvencimiento;
    private javax.swing.JTextField jTultimodigito;
    // End of variables declaration//GEN-END:variables
}
