/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recordatorio;

import BaseDatos.ConexionMySQL;
import BaseDatos.ConexionPostgresSQL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDRES TALERO
 */
public class GenerarNovedad extends javax.swing.JFrame {

    /**
     * Creates new form GenerarNovedad
     */
    public GenerarNovedad() {
        initComponents();
        jTidnovedad.setEnabled(false);
        jTrazonsocial.setEnabled(false);
        cargarnumero();
    }
    int aux=1;
    
    public void cargarnumero(){
      
        ConexionMySQL c = new ConexionMySQL();
        Connection cn = c.getConnection();
         Statement st2;
         
    try {
         
     String   sql1="select max(idnovedades) as cantidad from novedades;";
         
              st2 = cn.createStatement();
              ResultSet rs2 = st2.executeQuery(sql1);
              rs2.next();
              aux =rs2.getInt("cantidad");
              //System.out.println("cantidad"+aux);
                           
             
     } catch (SQLException ex) {
         
         JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA NUMERACION ");
         
     }
    aux++;
        
       jTidnovedad.setText(aux+"");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btngrabar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTidnovedad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jChretencion = new javax.swing.JCheckBox();
        jChicamensual = new javax.swing.JCheckBox();
        jChivabimestral = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jChivacuatrimestral = new javax.swing.JCheckBox();
        jChrentajuridica = new javax.swing.JCheckBox();
        jChexogenas = new javax.swing.JCheckBox();
        jChimpuestoalariqueza = new javax.swing.JCheckBox();
        jChrentapersonasnaturales = new javax.swing.JCheckBox();
        jChindustriaycomercio = new javax.swing.JCheckBox();
        jChcamaradecomercio = new javax.swing.JCheckBox();
        jChsupersociedades = new javax.swing.JCheckBox();
        jChicabimestral = new javax.swing.JCheckBox();
        jChproponentes = new javax.swing.JCheckBox();
        jChfonturtrimestral = new javax.swing.JCheckBox();
        jChregistronalturismo = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTnitocc = new javax.swing.JTextField();
        jTrazonsocial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NOVEDADES");

        jLabel1.setText("INGRESAR NOVEDAD");

        btngrabar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btngrabar.setText("GRABAR");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        jLabel4.setText("No ");

        jTidnovedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidnovedadActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jChretencion.setText("RETENCION Y CREE");
        jChretencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChretencionActionPerformed(evt);
            }
        });

        jChicamensual.setText("ICA MENSUAL");

        jChivabimestral.setText("IVA BIMESTRAL");
        jChivabimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChivabimestralActionPerformed(evt);
            }
        });

        jLabel3.setText("SELECCIONE  EL Ó LOS IMPUESTOS RESPETIVOS PARA LA EMPRESA:");

        jChivacuatrimestral.setText("IVA CUATRIMESTRAL");
        jChivacuatrimestral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChivacuatrimestralActionPerformed(evt);
            }
        });

        jChrentajuridica.setText("RENTA JURIDICA");
        jChrentajuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChrentajuridicaActionPerformed(evt);
            }
        });

        jChexogenas.setText("EXOGENAS");

        jChimpuestoalariqueza.setText("IMPUESTO A LA RIQUEZA");

        jChrentapersonasnaturales.setText("RENTA PERSONAS NATURALES");
        jChrentapersonasnaturales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChrentapersonasnaturalesActionPerformed(evt);
            }
        });

        jChindustriaycomercio.setText("INDUSTRIA Y COMERCIO GENERAL");

        jChcamaradecomercio.setText("CAMARA DE COMERCIO");

        jChsupersociedades.setText("SUPERSOCIEDADES");

        jChicabimestral.setText("ICA BIMESTRAL");

        jChproponentes.setText("PROPONENTES");

        jChfonturtrimestral.setText("FONTUR TRIMESTRAL");

        jChregistronalturismo.setText("REGISTRO NAL TURISMO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChretencion)
                            .addComponent(jChicabimestral)
                            .addComponent(jChivacuatrimestral)
                            .addComponent(jChivabimestral)
                            .addComponent(jChrentajuridica)
                            .addComponent(jChicamensual)
                            .addComponent(jChproponentes))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChrentapersonasnaturales)
                            .addComponent(jChcamaradecomercio)
                            .addComponent(jChindustriaycomercio)
                            .addComponent(jChsupersociedades)
                            .addComponent(jChimpuestoalariqueza)
                            .addComponent(jChfonturtrimestral)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jChexogenas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jChregistronalturismo)))))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChretencion)
                    .addComponent(jChexogenas)
                    .addComponent(jChregistronalturismo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChicamensual)
                    .addComponent(jChrentapersonasnaturales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChicabimestral)
                    .addComponent(jChcamaradecomercio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChivabimestral)
                    .addComponent(jChindustriaycomercio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChivacuatrimestral)
                    .addComponent(jChsupersociedades))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChproponentes)
                    .addComponent(jChimpuestoalariqueza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChrentajuridica)
                    .addComponent(jChfonturtrimestral))
                .addGap(40, 40, 40))
        );

        jLabel6.setText("NIT O CC");

        jTnitocc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnitoccActionPerformed(evt);
            }
        });
        jTnitocc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnitoccKeyTyped(evt);
            }
        });

        jLabel2.setText("Razon social");

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConsultar.setText("CONSULTAR TERCERO");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTnitocc)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidnovedad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTrazonsocial)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btngrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTidnovedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTnitocc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
  
    
    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn=mysql.getConnection();
        String checkbox1="",checkbox2="",checkbox3="",checkbox4="",checkbox5="",checkbox6="",
                checkbox7="",checkbox8="",checkbox9="",checkbox10="",checkbox11="",checkbox12="",
                checkbox13="",checkbox14="",checkbox15="";
        String sSQL="";
        String mensaje="";
          
        int cc=0,idnov=0;
        
        idnov = Integer.parseInt(jTidnovedad.getText());
        cc = Integer.parseInt(jTnitocc.getText());
        if(jChretencion.isSelected()==true){
        checkbox1=jChretencion.getText();
            
        }
        else{
        checkbox1="No presenta";
        }
        if(jChicamensual.isSelected()==true){
        checkbox2=jChicamensual.getText();
        }
        else{
        checkbox2="No presenta";
        }
        if(jChicabimestral.isSelected()==true){
        
        checkbox3=jChicabimestral.getText();
        }
        else{
        checkbox3="No presenta";
        }
        if(jChivabimestral.isSelected()==true){
           
        checkbox4=jChivabimestral.getText();
        
        }
        else{
        checkbox4="No presenta";
        }
        if(jChivacuatrimestral.isSelected()==true){
        checkbox5=jChivacuatrimestral.getText();
        
        }else{
        checkbox5="No presenta";
        }
        
        if(jChproponentes.isSelected()==true){
        checkbox6=jChproponentes.getText();
        }else{
        checkbox6="No presenta";
        }
        if(jChrentajuridica.isSelected()==true){
        checkbox7=jChrentajuridica.getText();
        
        
        }else{
        checkbox7="No presenta";
        }
        if(jChexogenas.isSelected()==true){
        checkbox8=jChexogenas.getText();
        
        
        }else{
        checkbox8="No presenta";
        }
        if(jChrentapersonasnaturales.isSelected()==true){
        checkbox9=jChrentapersonasnaturales.getText();
        }else{
        checkbox9="No presenta";
        }
        if(jChcamaradecomercio.isSelected()==true){
        checkbox10=jChcamaradecomercio.getText();
        }else{
        checkbox10="No presenta";
        }
        if(jChindustriaycomercio.isSelected()==true){
        checkbox11=jChindustriaycomercio.getText();
        }else{
        checkbox11="No presenta";
        }
        if(jChsupersociedades.isSelected()==true){
        checkbox12=jChsupersociedades.getText();
        }else{
        checkbox12="No presenta";
        }
        if(jChimpuestoalariqueza.isSelected()==true){
        checkbox13=jChimpuestoalariqueza.getText();
            
        }else{
        checkbox13="No presenta";
        }
        if(jChfonturtrimestral.isSelected()==true){
        checkbox14=jChfonturtrimestral.getText();
        
        }else{
        checkbox14="No presenta";
        }
        if(jChregistronalturismo.isSelected()==true){
        checkbox15=jChregistronalturismo.getText();
        }else{
        checkbox15="No presenta";
        }
        
        
        
        
            sSQL="INSERT INTO novedades(idnovedades, nnitocc, checkbox1, checkbox2, checkbox3, checkbox4,checkbox5, checkbox6, checkbox7, checkbox8, checkbox9, checkbox10,checkbox11, checkbox12, checkbox13, checkbox14, checkbox15) VALUES ( ?, ?, ?, ?,?, ?, ?, ?, ?, ?,?, ?, ?, ?, ?, ?,?);";
            mensaje="Los Datos se han Insertado de Manera Satisfactoria";
            
            

        
        try {
            PreparedStatement pst =cn.prepareStatement(sSQL);

            pst.setInt(1,idnov);
            pst.setInt(2,cc);
            pst.setString(3, checkbox1);
            pst.setString(4, checkbox2);
            pst.setString(5, checkbox3);
            pst.setString(6, checkbox4);
            pst.setString(7, checkbox5);
            pst.setString(8, checkbox6);
            pst.setString(9, checkbox7);
            pst.setString(10, checkbox8);
            pst.setString(11, checkbox9);
            pst.setString(12, checkbox10);
            pst.setString(13, checkbox11);
            pst.setString(14, checkbox12);
            pst.setString(15, checkbox13);
            pst.setString(16, checkbox14);
            pst.setString(17, checkbox15);
           
           
            
            int n=pst.executeUpdate();

            if(n > 0){

                JOptionPane.showMessageDialog(null,mensaje);

            }
            else {
                JOptionPane.showMessageDialog(null, "no se ha insertado nada ");

            }

        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        jTidnovedad.setText("");
        jTnitocc.setText("");
        jTrazonsocial.setText("");
        jChretencion.setEnabled(true);
        jChretencion.setSelected(false);
        jChicamensual.setEnabled(true);
        jChicamensual.setSelected(false);
        jChicabimestral.setSelected(false);
        jChivabimestral.setEnabled(true);
        jChivabimestral.setSelected(false);
        jChivacuatrimestral.setEnabled(true);
        jChivacuatrimestral.setSelected(false);
        jChproponentes.setSelected(false);
        jChrentajuridica.setEnabled(true);
        jChrentajuridica.setSelected(false);
        jChexogenas.setEnabled(true);
        jChexogenas.setSelected(false);
         jChrentapersonasnaturales.setEnabled(true);
        jChrentapersonasnaturales.setSelected(false);
        jChcamaradecomercio.setEnabled(true);
        jChcamaradecomercio.setSelected(false);
        jChindustriaycomercio.setEnabled(true);
        jChindustriaycomercio.setSelected(false);
        jChsupersociedades.setEnabled(true);
        jChsupersociedades.setSelected(false);
        jChimpuestoalariqueza.setEnabled(true);
        jChimpuestoalariqueza.setSelected(false);
        jChfonturtrimestral.setSelected(false);
        jChregistronalturismo.setSelected(false);
        cargarnumero();
    }//GEN-LAST:event_btngrabarActionPerformed

    private void jTnitoccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnitoccActionPerformed
        Cargardatos(jTnitocc.getText());
    }//GEN-LAST:event_jTnitoccActionPerformed

    private void jTnitoccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnitoccKeyTyped
char v= evt.getKeyChar();
        if(v<'0' || v>'9')evt.consume();
        
    
    }//GEN-LAST:event_jTnitoccKeyTyped

    private void jChivabimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChivabimestralActionPerformed
       if(jChivabimestral.isSelected()==true){
       jChivacuatrimestral.setEnabled(false);
              
       }
       else{
       jChivacuatrimestral.setEnabled(true);
      
       }
    }//GEN-LAST:event_jChivabimestralActionPerformed

    private void jChivacuatrimestralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChivacuatrimestralActionPerformed
         if(jChivacuatrimestral.isSelected()==true){
       jChivabimestral.setEnabled(false);
      
       
       }
       else{
       jChivabimestral.setEnabled(true);
       
       }
    }//GEN-LAST:event_jChivacuatrimestralActionPerformed

    private void jChrentajuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChrentajuridicaActionPerformed
         if(jChrentajuridica.isSelected()==true){
       jChrentapersonasnaturales.setEnabled(false);
             
       }
       else{
       jChrentapersonasnaturales.setEnabled(true);
       
       }
    }//GEN-LAST:event_jChrentajuridicaActionPerformed

    private void jChrentapersonasnaturalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChrentapersonasnaturalesActionPerformed
      if(jChrentapersonasnaturales.isSelected()==true){
       jChrentajuridica.setEnabled(false);
             
       }
       else{
       jChrentajuridica.setEnabled(true);
       
       }
    }//GEN-LAST:event_jChrentapersonasnaturalesActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn=mysql.getConnection();
        String razonsocial="";
        String sSQL="";
        String mensaje="";

        int idnov=0,n=0;

        idnov = Integer.parseInt(jTidnovedad.getText());

        try
        {
            JOptionPane optionPane = new JOptionPane();
            Object[] opciones={"Sí","No"};
            //Dialogo modal SI_NO
            int ret = JOptionPane.showOptionDialog(null,"Desea Borrar? ","Confirmar",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
            //Si la opcion escogida es Si
            if(ret==JOptionPane.YES_OPTION)
            {

                Statement stmt = cn.createStatement();
                n = stmt.executeUpdate("delete from novedades WHERE idnovedades= "+idnov);
                JOptionPane.showMessageDialog( null, "Registro Borrado "  ,
                    "Sistema", JOptionPane.ERROR_MESSAGE );
            }
        } catch (Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocurrio Un error" , "Atencion",
                JOptionPane.INFORMATION_MESSAGE);
        }

        jTidnovedad.setText("");
        jTnitocc.setText("");
        jTrazonsocial.setText("");
        jChretencion.setEnabled(true);
        jChretencion.setSelected(false);
        jChicamensual.setEnabled(true);
        jChicamensual.setSelected(false);
        jChicabimestral.setSelected(false);
        jChivabimestral.setEnabled(true);
        jChivabimestral.setSelected(false);
        jChivacuatrimestral.setEnabled(true);
        jChivacuatrimestral.setSelected(false);
        jChproponentes.setSelected(false);
        jChrentajuridica.setEnabled(true);
        jChrentajuridica.setSelected(false);
        jChexogenas.setEnabled(true);
        jChexogenas.setSelected(false);
         jChrentapersonasnaturales.setEnabled(true);
        jChrentapersonasnaturales.setSelected(false);
        jChcamaradecomercio.setEnabled(true);
        jChcamaradecomercio.setSelected(false);
        jChindustriaycomercio.setEnabled(true);
        jChindustriaycomercio.setSelected(false);
        jChsupersociedades.setEnabled(true);
        jChsupersociedades.setSelected(false);
        jChimpuestoalariqueza.setEnabled(true);
        jChimpuestoalariqueza.setSelected(false);
        jChfonturtrimestral.setSelected(false);
        jChregistronalturismo.setSelected(false);
        cargarnumero();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn=mysql.getConnection();
        String checkbox1="",checkbox2="",checkbox3="",checkbox4="",checkbox5="",checkbox6="",
                checkbox7="",checkbox8="",checkbox9="",checkbox10="",checkbox11="",checkbox12="",
                checkbox13="",checkbox14="",checkbox15="";
        String sSQL="";
        String mensaje="";

        int cc=0,idnov=0;
        
        idnov = Integer.parseInt(jTidnovedad.getText());
        cc = Integer.parseInt(jTnitocc.getText());
         
        if(jChretencion.isSelected()==true){
        checkbox1=jChretencion.getText();
        }
        else{
        checkbox1="No presenta";
        }
        if(jChicamensual.isSelected()==true){
        checkbox2=jChicamensual.getText();
        }
        else{
        checkbox2="No presenta";
        }
        if(jChicabimestral.isSelected()==true){
        
        checkbox3=jChicabimestral.getText();
        }
        else{
        checkbox3="No presenta";
        }
        if(jChivabimestral.isSelected()==true){
           
        checkbox4=jChivabimestral.getText();
        
        }
        else{
        checkbox4="No presenta";
        }
        if(jChivacuatrimestral.isSelected()==true){
        checkbox5=jChivacuatrimestral.getText();
        
        }else{
        checkbox5="No presenta";
        }
        
        if(jChproponentes.isSelected()==true){
        checkbox6=jChproponentes.getText();
        }else{
        checkbox6="No presenta";
        }
        if(jChrentajuridica.isSelected()==true){
        checkbox7=jChrentajuridica.getText();
        
        
        }else{
        checkbox7="No presenta";
        }
        if(jChexogenas.isSelected()==true){
        checkbox8=jChexogenas.getText();
        
        
        }else{
        checkbox8="No presenta";
        }
        if(jChrentapersonasnaturales.isSelected()==true){
        checkbox9=jChrentapersonasnaturales.getText();
        }else{
        checkbox9="No presenta";
        }
        if(jChcamaradecomercio.isSelected()==true){
        checkbox10=jChcamaradecomercio.getText();
        }else{
        checkbox10="No presenta";
        }
        if(jChindustriaycomercio.isSelected()==true){
        checkbox11=jChindustriaycomercio.getText();
        }else{
        checkbox11="No presenta";
        }
        if(jChsupersociedades.isSelected()==true){
        checkbox12=jChsupersociedades.getText();
        }else{
        checkbox12="No presenta";
        }
        if(jChimpuestoalariqueza.isSelected()==true){
        checkbox13=jChimpuestoalariqueza.getText();
            
        }else{
        checkbox13="No presenta";
        }
        if(jChfonturtrimestral.isSelected()==true){
        checkbox14=jChfonturtrimestral.getText();
        
        }else{
        checkbox14="No presenta";
        }
        if(jChregistronalturismo.isSelected()==true){
        checkbox15=jChregistronalturismo.getText();
        }else{
        checkbox15="No presenta";
        }
        
        
        
        
        
        sSQL="UPDATE novedades SET idnovedades=?,nnitocc=?, checkbox1=?, checkbox2=?, checkbox3=?,checkbox4=?,checkbox5=?, checkbox6=?, checkbox7=?, checkbox8=?, checkbox9=?, checkbox10=?,checkbox11=?, checkbox12=?, checkbox13=?, checkbox14=?, checkbox15=? WHERE idnovedades= "+idnov;
        mensaje="Los Datos se han actualizado de Manera Satisfactoria";

        

        try {
            PreparedStatement pst =cn.prepareStatement(sSQL);

            pst.setInt(1,idnov);
            pst.setInt(2,cc);
            pst.setString(3, checkbox1);
            pst.setString(4, checkbox2);
            pst.setString(5, checkbox3);
            pst.setString(6, checkbox4);
            pst.setString(7, checkbox5);
            pst.setString(8, checkbox6);
            pst.setString(9, checkbox7);
            pst.setString(10, checkbox8);
            pst.setString(11, checkbox9);
            pst.setString(12, checkbox10);
            pst.setString(13, checkbox11);
            pst.setString(14, checkbox12);
            pst.setString(15, checkbox13);
            pst.setString(16, checkbox14);
            pst.setString(17, checkbox15);
           
           

            int n=pst.executeUpdate();

            if(n > 0){

                JOptionPane.showMessageDialog(null,mensaje);

            }
            else {
                JOptionPane.showMessageDialog(null, "no se ha actualziado nada ");

            }

        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }

        jTidnovedad.setText("");
        jTnitocc.setText("");
        jTrazonsocial.setText("");
        jChretencion.setEnabled(true);
        jChretencion.setSelected(false);
        jChicamensual.setEnabled(true);
        jChicamensual.setSelected(false);
        jChicabimestral.setSelected(false);
        jChivabimestral.setEnabled(true);
        jChivabimestral.setSelected(false);
        jChivacuatrimestral.setEnabled(true);
        jChivacuatrimestral.setSelected(false);
        jChproponentes.setSelected(false);
        jChrentajuridica.setEnabled(true);
        jChrentajuridica.setSelected(false);
        jChexogenas.setEnabled(true);
        jChexogenas.setSelected(false);
         jChrentapersonasnaturales.setEnabled(true);
        jChrentapersonasnaturales.setSelected(false);
        jChcamaradecomercio.setEnabled(true);
        jChcamaradecomercio.setSelected(false);
        jChindustriaycomercio.setEnabled(true);
        jChindustriaycomercio.setSelected(false);
        jChsupersociedades.setEnabled(true);
        jChsupersociedades.setSelected(false);
        jChimpuestoalariqueza.setEnabled(true);
        jChimpuestoalariqueza.setSelected(false);
        jChfonturtrimestral.setSelected(false);
        jChregistronalturismo.setSelected(false);
        cargarnumero();
        
        
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        jTidnovedad.setText("");
        jTnitocc.setText("");
        jTrazonsocial.setText("");
        jChretencion.setEnabled(true);
        jChretencion.setSelected(false);
        jChicamensual.setEnabled(true);
        jChicamensual.setSelected(false);
        jChicabimestral.setSelected(false);
        jChivabimestral.setEnabled(true);
        jChivabimestral.setSelected(false);
        jChivacuatrimestral.setEnabled(true);
        jChivacuatrimestral.setSelected(false);
        jChproponentes.setSelected(false);
        jChrentajuridica.setEnabled(true);
        jChrentajuridica.setSelected(false);
        jChexogenas.setEnabled(true);
        jChexogenas.setSelected(false);
         jChrentapersonasnaturales.setEnabled(true);
        jChrentapersonasnaturales.setSelected(false);
        jChcamaradecomercio.setEnabled(true);
        jChcamaradecomercio.setSelected(false);
        jChindustriaycomercio.setEnabled(true);
        jChindustriaycomercio.setSelected(false);
        jChsupersociedades.setEnabled(true);
        jChsupersociedades.setSelected(false);
        jChimpuestoalariqueza.setEnabled(true);
        jChimpuestoalariqueza.setSelected(false);
        jChfonturtrimestral.setSelected(false);
        jChregistronalturismo.setSelected(false);
       cargarnumero();
        
        
            
            
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        consultatercero conte =new consultatercero();
        conte.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void jChretencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChretencionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChretencionActionPerformed

    private void jTidnovedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidnovedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidnovedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarNovedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarNovedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarNovedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarNovedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarNovedad().setVisible(true);
            }
        });
    }
    
    
        
    
    
    void Cargardatos(String valor) 
    {
       
    if(jTnitocc.getText().contentEquals("")){
     JOptionPane.showMessageDialog(null, "CAMPO (NIT O CC) VACIO" , "Atencion",
                               JOptionPane.INFORMATION_MESSAGE);
     
     
    }
     else{
     int resultado,vcod;
     vcod  =  Integer.parseInt(jTnitocc.getText());
     try{
     ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
         
         String ssql = "SELECT * FROM empresa " +
         "WHERE nitocc =" + vcod + "";
       Statement sst =cn.createStatement();
         ResultSet rst =sst.executeQuery(ssql);
         
        
        
        boolean seguir = rst.next();
                 if (seguir)
                  {
        
    String[] registro =new String[1];
    String[] datos =new String[16];
    String sSQL="";
     
    
     

    if(valor.equals(""))
    JOptionPane.showMessageDialog(null,"EL CAMPO ESTA VACIO");
       
    else  
    sSQL ="select razonsocial from empresa where nitocc = "+valor+"; ";
           try 
        {
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         
         
         while(rs.next())
         {
         
         registro[0]= rs.getString("razonsocial");
          jTrazonsocial.setText(registro[0]);
         }
         } 
        catch (SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex);
            
        }
        
         sSQL ="select idnovedades,checkbox1,checkbox2,checkbox3,checkbox4,checkbox5,checkbox6,checkbox7,checkbox8,checkbox9,checkbox10,checkbox11,checkbox12,checkbox13,checkbox14,checkbox15 from novedades where nnitocc = "+valor+"; ";
           try 
        {
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         
         
         while(rs.next())
         {
         
         datos[0]= rs.getString("idnovedades");
         jTidnovedad.setText(datos[0]);
         datos[1]=rs.getString("checkbox1");
         
                 
         if(datos[1].contentEquals("RETENCION Y CREE"))
         {
         jChretencion.setSelected(true);
         }
         datos[2]= rs.getString("checkbox2");
         if(datos[2].contentEquals("ICA MENSUAL"))
         {
         jChicamensual.setSelected(true);
         }
         datos[3]= rs.getString("checkbox3");
         if(datos[3].contentEquals("ICA BIMESTRAL"))
         {
         jChicabimestral.setSelected(true);
         }
         datos[4]= rs.getString("checkbox4");
         if(datos[4].contentEquals("IVA BIMESTRAL"))
         {
         jChivabimestral.setSelected(true);
         jChivacuatrimestral.setEnabled(false);
         
         
         }
         datos[5]= rs.getString("checkbox5");
         if(datos[5].contentEquals("IVA CUATRIMESTRAL"))
         {
             jChivabimestral.setEnabled(false);
         jChivacuatrimestral.setSelected(true);
         
         }
         
         datos[6]= rs.getString("checkbox6");
         if(datos[6].contentEquals("PROPONENTES"))
         {
         jChproponentes.setSelected(true);
         
         }
         datos[7]= rs.getString("checkbox7");
         if(datos[7].contentEquals("RENTA JURIDICA"))
         {
         jChrentajuridica.setSelected(true);
         jChrentapersonasnaturales.setEnabled(false);
         }
         datos[8]= rs.getString("checkbox8");
         if(datos[8].contentEquals("EXOGENAS"))
         {
        jChexogenas.setSelected(true);
         }
         datos[9]= rs.getString("checkbox9");
         if(datos[9].contentEquals("RENTA PERSONAS NATURALES"))
         {
         jChrentapersonasnaturales.setSelected(true);
         jChrentajuridica.setEnabled(false);
         
         }
         datos[10]= rs.getString("checkbox10");
         if(datos[10].contentEquals("CAMARA DE COMERCIO"))
         {
         jChcamaradecomercio.setSelected(true);
         }
         datos[11]= rs.getString("checkbox11");
         if(datos[11].contentEquals("INDUSTRIA Y COMERCIO GENERAL"))
         {
         jChindustriaycomercio.setSelected(true);
         }
         datos[12]= rs.getString("checkbox12");
         if(datos[12].contentEquals("SUPERSOCIEDADES"))
         {
         jChsupersociedades.setSelected(true);
         }
         datos[13]= rs.getString("checkbox13");
         if(datos[13].contentEquals("IMPUESTO A LA RIQUEZA"))
         {
         jChimpuestoalariqueza.setSelected(true);
         }
         datos[14]= rs.getString("checkbox14");
         if(datos[14].contentEquals("FONTUR TRIMESTRAL"))
         {
         jChfonturtrimestral.setSelected(true);
         }
         datos[15]= rs.getString("checkbox15");
         if(datos[15].contentEquals("REGISTRO NAL TURISMO"))
         {
         jChregistronalturismo.setSelected(true);
         }
         
         }
         }
        catch (SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex);
            
        }
        
       }else{
                      JOptionPane.showMessageDialog( null, "No existe  "  ,
                      "Error ...", JOptionPane.ERROR_MESSAGE );
                      
           int returnVal = JOptionPane.showConfirmDialog(this, "Desea Crear la Empresa?");
           if(returnVal == JOptionPane.YES_OPTION){
               Terceros te = new Terceros();
           te.setVisible(true);
           te.cargarnitocc(valor);
                 }
              
     }}catch(Exception e){
           
           e.printStackTrace();
                               JOptionPane.showMessageDialog(null, "Ocurrio Un error" , "Atencion",
                               JOptionPane.INFORMATION_MESSAGE);
       
       
       }
     
     
                 
       
    }}
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btngrabar;
    private javax.swing.JCheckBox jChcamaradecomercio;
    private javax.swing.JCheckBox jChexogenas;
    private javax.swing.JCheckBox jChfonturtrimestral;
    private javax.swing.JCheckBox jChicabimestral;
    private javax.swing.JCheckBox jChicamensual;
    private javax.swing.JCheckBox jChimpuestoalariqueza;
    private javax.swing.JCheckBox jChindustriaycomercio;
    private javax.swing.JCheckBox jChivabimestral;
    private javax.swing.JCheckBox jChivacuatrimestral;
    private javax.swing.JCheckBox jChproponentes;
    private javax.swing.JCheckBox jChregistronalturismo;
    private javax.swing.JCheckBox jChrentajuridica;
    private javax.swing.JCheckBox jChrentapersonasnaturales;
    private javax.swing.JCheckBox jChretencion;
    private javax.swing.JCheckBox jChsupersociedades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTidnovedad;
    private javax.swing.JTextField jTnitocc;
    private javax.swing.JTextField jTrazonsocial;
    // End of variables declaration//GEN-END:variables
}
