/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recordatorio;

import BaseDatos.ConexionMySQL;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ANDRES TALERO
 */
public class Terceros extends javax.swing.JFrame {
Date ahora = new Date();
    /**
     * Creates new form Terceros
     */
    public Terceros() {
        initComponents();
        jTdv.setEditable(false);
       jTdv.setEnabled(false);
       cargardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTnitocc = new javax.swing.JTextField();
        jTdv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jtrazonsocial = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtrepresentantelegal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fechavenresolfact = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        cmbactp = new javax.swing.JComboBox<>();
        txtnomactp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttarifaactp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbacts = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtnomacts = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttarifaacts = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtnomactt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbactt = new javax.swing.JComboBox<>();
        txttarifaactt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtnomactc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbactc = new javax.swing.JComboBox<>();
        txttarifaactc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TERCEROS");
        setPreferredSize(new java.awt.Dimension(750, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("INGRESE LA INFORMACION DE LA EMPRESA");

        jLabel2.setText("NIT O CC");

        JTnitocc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTnitoccActionPerformed(evt);
            }
        });
        JTnitocc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTnitoccKeyTyped(evt);
            }
        });

        jTdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdvActionPerformed(evt);
            }
        });

        jLabel3.setText("DV");

        jLabel4.setText("RAZON SOCIAL ");

        Jtrazonsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtrazonsocialActionPerformed(evt);
            }
        });
        Jtrazonsocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtrazonsocialKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtrazonsocialKeyTyped(evt);
            }
        });

        btnGrabar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel5.setText("REPRESENTANTE LEGAL");

        txtrepresentantelegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrepresentantelegalActionPerformed(evt);
            }
        });

        jLabel6.setText("DIRECCION");

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });

        jLabel7.setText("TELEFONO");

        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        jLabel8.setText("FECHA VENCIMIENTO NUMERACION DE FACTURACION");

        fechavenresolfact.setDateFormatString("yyyy/MM/dd");

        jLabel9.setText("ACTIVIDAD PRINCIPAL");

        cmbactp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbactpActionPerformed(evt);
            }
        });

        txtnomactp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomactpActionPerformed(evt);
            }
        });

        jLabel10.setText("NOMBRE CODIGO CIU");

        jLabel11.setText("TARIFA ACTIVIDAD PRINCIPAL");

        txttarifaactp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarifaactpActionPerformed(evt);
            }
        });

        jLabel12.setText("ACTIVIDAD SECUNDARIA");

        cmbacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbactsActionPerformed(evt);
            }
        });

        jLabel13.setText("NOMBRE CODIGO CIU");

        txtnomacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomactsActionPerformed(evt);
            }
        });

        jLabel14.setText("TARIFA ACTIVIDAD SECUNDARIA");

        txttarifaacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarifaactsActionPerformed(evt);
            }
        });

        jLabel15.setText("ACTIVIDAD 3");

        txtnomactt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomacttActionPerformed(evt);
            }
        });

        jLabel16.setText("NOMBRE CODIGO CIU");

        jLabel17.setText("TARIFA ACTIVIDAD 3");

        cmbactt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbacttActionPerformed(evt);
            }
        });

        txttarifaactt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarifaacttActionPerformed(evt);
            }
        });

        jLabel18.setText("ACTIVIDAD 4");

        txtnomactc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomactcActionPerformed(evt);
            }
        });

        jLabel19.setText("NOMBRE CODIGO CIU");

        jLabel20.setText("TARIFA ACTIVIDAD 4");

        cmbactc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbactcActionPerformed(evt);
            }
        });

        txttarifaactc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttarifaactcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(7, 7, 7)
                                .addComponent(cmbactp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnomactp, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Jtrazonsocial))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JTnitocc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTdv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtrepresentantelegal, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechavenresolfact, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttarifaactp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbacts, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnomacts, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttarifaacts, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbactt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnomactt, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttarifaactt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbactc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnomactc, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttarifaactc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGrabar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTnitocc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Jtrazonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtrepresentantelegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(fechavenresolfact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbactp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtnomactp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txttarifaactp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtnomacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txttarifaacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbactt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtnomactt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txttarifaactt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbactc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(txtnomactc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txttarifaactc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTnitoccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTnitoccActionPerformed
JTnitocc.transferFocus();
digitoverificacion();
   //  Cargartercero(JTnitocc.getText());

    }//GEN-LAST:event_JTnitoccActionPerformed

    
    void Cargartercero(String valor)
    {
    
    String[] registro =new String[13];    
    String sSQL="";
     
    ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
     

    if(valor.equals(""))
    JOptionPane.showMessageDialog(null,"EL CAMPO ESTA VACIO");
       
    else  
    sSQL ="select razonsocial,representantelegal,direccion,telefono,fecharesolucion,actp,tarifaactp,acts,tarifaacts,actt,tarifaactt,actc,tarifaactc from empresa where nitocc = "+valor+"; ";
           try 
        {
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         
         
         while(rs.next())
         {
         
         registro[0]= rs.getString("razonsocial");
         registro[1]= rs.getString("representantelegal");
         registro[2]= rs.getString("direccion");
         registro[3]= rs.getString("telefono");
         registro[4]= rs.getString("fecharesolucion");
         registro[5]= rs.getString("actp");
         registro[6]= rs.getString("tarifaactp");
         registro[7]= rs.getString("acts");
         registro[8]= rs.getString("tarifaacts");
         registro[9]= rs.getString("actt");
         registro[10]= rs.getString("tarifaactt");
         registro[11]= rs.getString("actc");
         registro[12]= rs.getString("tarifaactc");
        
             Jtrazonsocial.setText(registro[0]);
             txtrepresentantelegal.setText(registro[1]);
             txtdireccion.setText(registro[2]);
             txttelefono.setText(registro[3]);
             
             Recordatorio re =new  Recordatorio();
             String fecha =registro[4];
             
             System.out.println("fecha"+fecha);
             fechavenresolfact.setDate(re.deStringToDate(fecha));
             cmbactp.setSelectedIndex(Integer.parseInt(registro[5]));
             
             txttarifaactp.setText(registro[6]);
             cmbacts.setSelectedIndex(Integer.parseInt(registro[7]));
             txttarifaacts.setText(registro[8]);
             cmbactt.setSelectedIndex(Integer.parseInt(registro[9]));
             txttarifaactt.setText(registro[10]);
             cmbactc.setSelectedIndex(Integer.parseInt(registro[11]));
             txttarifaactc.setText(registro[12]);
         
         }
         
         
        } 
        catch (SQLException ex) 
        {
           JOptionPane.showMessageDialog(null, ex);
            
        }
           
          
           
         
    }
    
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
    
    void  digitoverificacion(){ 
        
 String nit1,nit2;
 int x,y,vpri[],z,dv1,i;
 
 nit1=JTnitocc.getText();
	if (nit1=="" || nit1==null)
	{
 	JOptionPane.showMessageDialog(null,"El valor digitado no es un numero valido");		
	} else {
  vpri = new int[16]; 
 	x=0;
        y=0; 
        
        
 	vpri[1]=3;
 	vpri[2]=7;
 	vpri[3]=13; 
 	vpri[4]=17;
 	vpri[5]=19;
 	vpri[6]=23;
 	vpri[7]=29;
 	vpri[8]=37;
 	vpri[9]=41;
 	vpri[10]=43;
 	vpri[11]=47;  
 	vpri[12]=53;  
 	vpri[13]=59; 
 	vpri[14]=67; 
 	vpri[15]=71;
        
        z=nit1.length();
  
        for(i=0; i<z; i++)
 	{ 
 	 
       y =(Integer.parseInt(nit1.substring(i,1+i)));
             
       x+=(y*vpri[z-i]);
   
 	}
        
  y=x%11;
 	
  if (y > 1)
 	{
   dv1=11-y;
 	} else {
   dv1=y;
 	}
  nit2=Integer.toString(dv1);
 	jTdv.setText(nit2);
        }
       }
    //actividad primaria
    public void cargaractividad(String dato) {
    String sSQL="";
    
    
    if(cmbactp.getSelectedItem() == null){
             txtnomactp.setText("");
             txttarifaactp.setText("");
         }else{
    sSQL ="select actividad, tarifa from actividadeseconomicas where idcodigo = "+dato+";";
    try 
        {
            ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         txtnomactp.setText("");
         txttarifaactp.setText("");
         
         while(rs.next())
         {
             txtnomactp.setText(rs.getString(1));
         txttarifaactp.setText(rs.getString(2));
         
         
          }} 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA LISTA DE ACTIVIDADES ECONOMICAS ");
        }
    }



}
    
// actividad secundaria

public void cargaractividads(String dato) {
    String sSQL="";
    
    
    if(cmbacts.getSelectedItem() == null){
             txtnomacts.setText("");
             txttarifaacts.setText("");
         }else{
    sSQL ="select actividad, tarifa from actividadeseconomicas where idcodigo = "+dato+";";
    try 
        {
            ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         txtnomacts.setText("");
         txttarifaacts.setText("");
         
         while(rs.next())
         {
             txtnomacts.setText(rs.getString(1));
         txttarifaacts.setText(rs.getString(2));
         
         
          }} 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA LISTA DE ACTIVIDADES ECONOMICAS ");
        }
    }



}    
    

//actividad terciaria


public void cargaractividadt(String dato) {
    String sSQL="";
    
    
    if(cmbactt.getSelectedItem() == null){
             txtnomactt.setText("");
             txttarifaactt.setText("");
         }else{
    sSQL ="select actividad, tarifa from actividadeseconomicas where idcodigo = "+dato+";";
    try 
        {
            ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         txtnomactt.setText("");
         txttarifaactt.setText("");
         
         while(rs.next())
         {
             txtnomactt.setText(rs.getString(1));
         txttarifaactt.setText(rs.getString(2));
         
         
          }} 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA LISTA DE ACTIVIDADES ECONOMICAS ");
        }
    }



}  
    //actividad cuarta
public void cargaractividadc(String dato) {
    String sSQL="";
    
    
    if(cmbactc.getSelectedItem() == null){
             txtnomactc.setText("");
             txttarifaactc.setText("");
         }else{
    sSQL ="select actividad, tarifa from actividadeseconomicas where idcodigo = "+dato+";";
    try 
        {
            ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         txtnomactc.setText("");
         txttarifaactc.setText("");
         
         while(rs.next())
         {
             txtnomactc.setText(rs.getString(1));
         txttarifaactc.setText(rs.getString(2));
         
         
          }} 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA LISTA DE ACTIVIDADES ECONOMICAS ");
        }
    }



}  

    
    
    
    
    
    
    public void cargardatos() {
    String sSQL="";
    
    
    
    sSQL ="select idcodigo from actividadeseconomicas where idcodigo = idcodigo;";
    try 
        {
            ConexionMySQL mysql = new ConexionMySQL();
    Connection cn=mysql.getConnection();
         Statement st =cn.createStatement();
         ResultSet rs =st.executeQuery(sSQL);
         cmbactp.removeAllItems();
         cmbacts.removeAllItems();
         cmbactt.removeAllItems();
         cmbactc.removeAllItems();
         cmbactp.addItem(null);
         cmbacts.addItem(null);
         cmbactt.addItem(null);
         cmbactc.addItem(null);
         while(rs.next())
         {
         cmbactp.addItem(rs.getString(1));
         cmbacts.addItem(rs.getString(1));
         cmbactt.addItem(rs.getString(1));
         cmbactc.addItem(rs.getString(1));
         
         
          }} 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
            JOptionPane.showMessageDialog(null, "NO SE HA PODIDO CARGAR LA LISTA DE ACTIVIDADES ECONOMICAS ");
        }
    



}
      
    
    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
                                               
         
                
                
                    Recordatorio re =new  Recordatorio();
                    
                    
                    ConexionMySQL mysql = new ConexionMySQL();
                    Connection cn=mysql.getConnection();
                    String razonsocial="",representantelegal="",direccion="",
                            telefono="",tarifaactp="",tarifaacts="",tarifaactt="",tarifaactc="";
                    
                    String fecharesolucion="";
                   

                    
                    
                    String sSQL="";
                    String mensaje="";
                    
                    int cc=0,dv=0,actp=0,acts=0,actt=0,actc=0;
                    
                    cc = Integer.parseInt(JTnitocc.getText());
                    dv = Integer.parseInt(jTdv.getText());
                    razonsocial= Jtrazonsocial.getText();
                    representantelegal= txtrepresentantelegal.getText();
                    direccion=txtdireccion.getText();
                    telefono= txttelefono.getText();
                    fecharesolucion=re.getFechaActual(fechavenresolfact.getDate());
                  
                    System.out.println("fecha resolucion"+fecharesolucion);
                    
                    
                    
                    
                    if(cmbactp.getSelectedItem() != null){
                        actp= cmbactp.getSelectedIndex();
                        tarifaactp=txttarifaactp.getText();
                    } else {
                        actp=0;
                        tarifaactp=null;
                        
                    }
                    if(cmbacts.getSelectedItem() != null){
                        acts= cmbacts.getSelectedIndex();
                        tarifaacts=txttarifaacts.getText();
                    } else {
                        acts=0;
                        tarifaacts=null;
                        
                    }
                    if(cmbactt.getSelectedItem() != null){
                        actt= cmbactt.getSelectedIndex();
                        tarifaactt=txttarifaactt.getText();
                    } else {
                        actt=0;
                        tarifaactt=null;
                        
                    }
                    if(cmbactc.getSelectedItem() != null){
                        actc= cmbactc.getSelectedIndex();
                        tarifaactc=txttarifaactc.getText();
                    } else {
                        actc=0;
                        tarifaactc=null;
                        
                    }
                    
                    
                    
                    
                    
                    
                    
                    
                    sSQL="INSERT INTO empresa(nitocc,dv,razonsocial,representantelegal,direccion,telefono,fecharesolucion,actp,tarifaactp,acts,tarifaacts,actt,tarifaactt,actc,tarifaactc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    mensaje="Los Datos se han Insertado de Manera Satisfactoria";
                    
                    JTnitocc.setText("");
                    jTdv.setText("");
                    Jtrazonsocial.setText("");
                    txtrepresentantelegal.setText("");
                    txtdireccion.setText("");
                    txttelefono.setText("");
                    fechavenresolfact.setDate(ahora);
                    cmbactp.setSelectedIndex(0);
                    txttarifaactp.setText("");
                    cmbacts.setSelectedIndex(0);
                    txttarifaacts.setText("");
                    cmbactt.setSelectedIndex(0);
                    txttarifaactt.setText("");
                    cmbactc.setSelectedIndex(0);
                    txttarifaactc.setText("");
                    
                    
                    
                    
                    
                    try {
                        PreparedStatement pst =cn.prepareStatement(sSQL);
                        
                        pst.setInt(1,cc);
                        pst.setInt(2,dv);
                        pst.setString(3,razonsocial);
                        pst.setString(4,representantelegal);
                        pst.setString(5,direccion);
                        pst.setString(6,telefono);
                        pst.setString(7, fecharesolucion);
                        pst.setInt(8,actp);
                        pst.setString(9,tarifaactp);
                        pst.setInt(10,acts);
                        pst.setString(11,tarifaacts);
                        pst.setInt(12,actt);
                        pst.setString(13,tarifaactt);
                        pst.setInt(14,actc);
                        pst.setString(15,tarifaactc);
                        
                        int n=pst.executeUpdate();
                        
                        if(n > 0){
                            
                            JOptionPane.showMessageDialog(null,mensaje);
                            
                        }
                        else {
                            JOptionPane.showMessageDialog(null, "no se ha insertado nada ");
                            
                        }
                        
                    }
                    catch (SQLException ex)
                    {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                    JTnitocc.requestFocus();
                    
                    
                    
                    
                    
                    
                
               
                
                
            
            
        
        
    }//GEN-LAST:event_btnGrabarActionPerformed

    
    public void convertiraMayusculasEnJtextfield(javax.swing.JTextField jTextfieldS){
String cadena= (Jtrazonsocial.getText()).toUpperCase();
Jtrazonsocial.setText(cadena);
}
    
    private void JtrazonsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtrazonsocialActionPerformed
        Jtrazonsocial.transferFocus();
        
    }//GEN-LAST:event_JtrazonsocialActionPerformed

    private void jTdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdvActionPerformed
       jTdv.transferFocus();
       
    }//GEN-LAST:event_jTdvActionPerformed

    private void JtrazonsocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtrazonsocialKeyReleased
       convertiraMayusculasEnJtextfield(Jtrazonsocial);
    }//GEN-LAST:event_JtrazonsocialKeyReleased

    private void JtrazonsocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtrazonsocialKeyTyped
        
    }//GEN-LAST:event_JtrazonsocialKeyTyped

    private void JTnitoccKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTnitoccKeyTyped
char v = evt.getKeyChar();
        if(v<'0' || v>'9')evt.consume();        // TODO add your handling code here:
    }//GEN-LAST:event_JTnitoccKeyTyped

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
Recordatorio re =new  Recordatorio();
                 
                    
                    ConexionMySQL mysql = new ConexionMySQL();
                    Connection cn=mysql.getConnection();
                    String razonsocial="",representantelegal="",direccion="",
                            telefono="",tarifaactp="",tarifaacts="",tarifaactt="",tarifaactc="";
                    
                    String fecharesolucion="";
                   

                    
                    
                    String sSQL="";
                    String mensaje="";
                    
                    int cc=0,dv=0,actp=0,acts=0,actt=0,actc=0;
                    
                    cc = Integer.parseInt(JTnitocc.getText());
                    dv = Integer.parseInt(jTdv.getText());
                    razonsocial= Jtrazonsocial.getText();
                    representantelegal= txtrepresentantelegal.getText();
                    direccion=txtdireccion.getText();
                    telefono= txttelefono.getText();
                    fecharesolucion=re.getFechaActual(fechavenresolfact.getDate());
                  
                    System.out.println("fecha resolucion"+fecharesolucion);
                    
                    
                    
                    
                    if(cmbactp.getSelectedItem() != null){
                        actp= cmbactp.getSelectedIndex();
                        tarifaactp=txttarifaactp.getText();
                    } else {
                        actp=0;
                        tarifaactp=null;
                        
                    }
                    if(cmbacts.getSelectedItem() != null){
                        acts= cmbacts.getSelectedIndex();
                        tarifaacts=txttarifaacts.getText();
                    } else {
                        acts=0;
                        tarifaacts=null;
                        
                    }
                    if(cmbactt.getSelectedItem() != null){
                        actt= cmbactt.getSelectedIndex();
                        tarifaactt=txttarifaactt.getText();
                    } else {
                        actt=0;
                        tarifaactt=null;
                        
                    }
                    if(cmbactc.getSelectedItem() != null){
                        actc= cmbactc.getSelectedIndex();
                        tarifaactc=txttarifaactc.getText();
                    } else {
                        actc=0;
                        tarifaactc=null;
                        
                    }

        sSQL="UPDATE empresa SET nitocc=?,dv=?,razonsocial=?,representantelegal=?,direccion=?,telefono=?,fecharesolucion=?,actp=?,tarifaactp=?,acts=?,tarifaacts=?,actt=?,tarifaactt=?,actc=?,tarifaactc=? WHERE nitocc= "+cc;

            mensaje="Los Datos se han actualizado de Manera Satisfactoria";
            
            JTnitocc.setText("");
                    jTdv.setText("");
                    Jtrazonsocial.setText("");
                    txtrepresentantelegal.setText("");
                    txtdireccion.setText("");
                    txttelefono.setText("");
                    fechavenresolfact.setDate(ahora);
                    cmbactp.setSelectedIndex(0);
                    txttarifaactp.setText("");
                    cmbacts.setSelectedIndex(0);
                    txttarifaacts.setText("");
                    cmbactt.setSelectedIndex(0);
                    txttarifaactt.setText("");
                    cmbactc.setSelectedIndex(0);
                    txttarifaactc.setText("");
            
            try {
            PreparedStatement pst =cn.prepareStatement(sSQL);

           pst.setInt(1,cc);
           pst.setInt(2,dv);
           pst.setString(3,razonsocial);
           pst.setString(4,representantelegal);
           pst.setString(5,direccion);
           pst.setString(6,telefono);
           pst.setString(7, fecharesolucion);
           pst.setInt(8,actp);
           pst.setString(9,tarifaactp);
           pst.setInt(10,acts);
           pst.setString(11,tarifaacts);
           pst.setInt(12,actt);
           pst.setString(13,tarifaactt);
           pst.setInt(14,actc);
           pst.setString(15,tarifaactc);
            

            int n=pst.executeUpdate();

            if(n > 0){

                JOptionPane.showMessageDialog(null,mensaje);

            }
            else {
                JOptionPane.showMessageDialog(null, "no se ha actualziado nada ");

            }

        }
        catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
            
            
            
            
            
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn=mysql.getConnection();
        String razonsocial="";
        String sSQL="";
        String mensaje="";
        
        int cc=0,n=0;
        
        cc = Integer.parseInt(JTnitocc.getText());           
        
        
        try
                      {
                        JOptionPane optionPane = new JOptionPane();
	                    Object[] opciones={"Sí","No"};
	                    //Dialogo modal SI_NO
	                     int ret = JOptionPane.showOptionDialog(null,"Desea Borrar? ","Confirmar",
                         JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones,opciones[0]);
	                     //Si la opcion escogida es Si
	                     if(ret==JOptionPane.YES_OPTION)
                         {
                             
                             
                             Statement stmt = cn.createStatement();
                              n = stmt.executeUpdate("delete from empresa WHERE nitocc= "+cc);
                              JOptionPane.showMessageDialog( null, "Registro Borrado "  ,
                                "Sistema", JOptionPane.ERROR_MESSAGE );
                         }
                      } catch (Exception e)
                      {
                               e.printStackTrace();
                               JOptionPane.showMessageDialog(null, "Ocurrio Un error" , "Atencion",
                               JOptionPane.INFORMATION_MESSAGE);
                      }
            
              JTnitocc.setText("");
                    jTdv.setText("");
                    Jtrazonsocial.setText("");
                    txtrepresentantelegal.setText("");
                    txtdireccion.setText("");
                    txttelefono.setText("");
                    fechavenresolfact.setDate(ahora);
                    cmbactp.setSelectedIndex(0);
                    txttarifaactp.setText("");
                    cmbacts.setSelectedIndex(0);
                    txttarifaacts.setText("");
                    cmbactt.setSelectedIndex(0);
                    txttarifaactt.setText("");
                    cmbactc.setSelectedIndex(0);
                    txttarifaactc.setText("");
            
           

              

        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      JTnitocc.setText("");
                    jTdv.setText("");
                    Jtrazonsocial.setText("");
                    txtrepresentantelegal.setText("");
                    txtdireccion.setText("");
                    txttelefono.setText("");
                    fechavenresolfact.setDate(ahora);
                    cmbactp.setSelectedIndex(0);
                    txttarifaactp.setText("");
                    cmbacts.setSelectedIndex(0);
                    txttarifaacts.setText("");
                    cmbactt.setSelectedIndex(0);
                    txttarifaactt.setText("");
                    cmbactc.setSelectedIndex(0);
                    txttarifaactc.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        consultatercero conte =new consultatercero();
        conte.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtrepresentantelegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrepresentantelegalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrepresentantelegalActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txttarifaactpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarifaactpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttarifaactpActionPerformed

    private void txtnomactpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomactpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomactpActionPerformed

    private void txtnomactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomactsActionPerformed

    private void txttarifaactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarifaactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttarifaactsActionPerformed

    private void txtnomacttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomacttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomacttActionPerformed

    private void txttarifaacttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarifaacttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttarifaacttActionPerformed

    private void txtnomactcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomactcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomactcActionPerformed

    private void txttarifaactcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttarifaactcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttarifaactcActionPerformed

    private void cmbactpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbactpActionPerformed
          cargaractividad((String) cmbactp.getSelectedItem());
       
       
    }//GEN-LAST:event_cmbactpActionPerformed

    private void cmbactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbactsActionPerformed
  cargaractividads((String) cmbacts.getSelectedItem());        // TODO add your handling code here:
    }//GEN-LAST:event_cmbactsActionPerformed

    private void cmbacttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbacttActionPerformed
       cargaractividadt((String) cmbactt.getSelectedItem());  // TODO add your handling code here:
    }//GEN-LAST:event_cmbacttActionPerformed

    private void cmbactcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbactcActionPerformed
       cargaractividadc((String) cmbactt.getSelectedItem());// TODO add your handling code here:
    }//GEN-LAST:event_cmbactcActionPerformed

    
    public void cargarnitocc(String nitocc){
    
    
        JTnitocc.setText(nitocc);
    
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terceros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terceros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTnitocc;
    private javax.swing.JTextField Jtrazonsocial;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbactc;
    private javax.swing.JComboBox<String> cmbactp;
    private javax.swing.JComboBox<String> cmbacts;
    private javax.swing.JComboBox<String> cmbactt;
    private com.toedter.calendar.JDateChooser fechavenresolfact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTdv;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnomactc;
    private javax.swing.JTextField txtnomactp;
    private javax.swing.JTextField txtnomacts;
    private javax.swing.JTextField txtnomactt;
    private javax.swing.JTextField txtrepresentantelegal;
    private javax.swing.JTextField txttarifaactc;
    private javax.swing.JTextField txttarifaactp;
    private javax.swing.JTextField txttarifaacts;
    private javax.swing.JTextField txttarifaactt;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
